name: Tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go build -v ./...
      - run: go vet ./...
      - name: gofmt
        run: test -z "$(gofmt -s -l .)" || (gofmt -s -l . && exit 1)

  generate:
    name: Docs up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' and commit."; exit 1)

  test:
    name: Unit & Acceptance (mock)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.9.*"
          - "1.10.*"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - name: Acceptance tests against mocked Provisioning API
        env:
          TF_ACC: "1"
        run: go test ./... -v -timeout=120m
